export type Month =
  | 'january' | 'february' | 'march' | 'april'
  | 'may' | 'june' | 'july' | 'august'
  | 'september' | 'october' | 'november' | 'december';

export type Mode = 'light' | 'dark';

// Single scene per month - self-contained spot illustrations
// Base character - footwear specified per activity in each prompt
export const CHARACTER_DESC = 'single person, one man only, friendly young caucasian man in his early 30s, slim thin athletic build, lean body type, medium height, exactly two arms, exactly two hands with five fingers each, exactly two legs, short neat blonde hair with natural texture, light blonde eyebrows, visible light stubble beard covering jaw and chin, fair skin with slight tan, friendly long face shape, bright vivid blue eyes looking straight ahead not cross-eyed, larger than average nose, friendly slight smile showing no teeth, normal human ears, natural human proportions, gold wedding ring on left ring finger';

// Background colors
export const LIGHT_BACKGROUND = '#fafafa';
export const DARK_BACKGROUND = '#1a1025';

export const LIGHT_BASE_STYLE = `3D render, Pixar Disney animation style, soft lighting, vibrant colors, highly detailed, cute, solid white background, simple minimalist scene, anatomically correct human with exactly two arms and exactly two legs, slim thin athletic body, lean proportions, clear visible ground plane, sharp clean outlines, crisp edges, high contrast between subject and background, isolated subject, single character only, IMPORTANT: center-focused composition with all key elements and subject tightly grouped in the middle of the frame, keep edges and corners empty, vignette-safe layout`;

export const DARK_BASE_STYLE = `3D render, Pixar Disney animation style, warm moody lighting, rich colors, highly detailed, cute, solid dark purple background, simple minimalist scene, anatomically correct human with exactly two arms and exactly two legs, slim thin body even when lying down sleeping or relaxed never fat or overweight, lean athletic proportions maintained in all poses including sleeping, clear visible ground plane, sharp clean outlines, crisp edges, high contrast between subject and background, isolated subject, single character only, IMPORTANT: center-focused composition with all key elements and subject tightly grouped in the middle of the frame, keep edges and corners empty, vignette-safe layout`;

// Light mode: Active activities while still working/coding - absurd multitasking
export const LIGHT_PROMPTS: Record<Month, string> = {
  january: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} skiing down a pristine Swiss alpine slope at full speed, dynamic carving pose with skis cutting through fresh powder, wearing stylish baby blue ski jacket, black ski trousers, ski boots, shiny blue titanium-finish ski goggles pushed up on forehead, holding open MacBook laptop in both hands while skiing, looking intently at screen with focused coding expression, snowy Swiss mountain peaks in background, bright sunny winter day, action shot with snow spray, absurdly multitasking, compact centered composition`,

  february: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} sitting in ergonomic desk chair at cozy home office with clay pink walls and natural wood acoustic panels, wearing thick chunky cream cable-knit sweater, warm grey beanie pulled down on head, comfortable fluffy sheepskin slippers on feet, MacBook laptop connected to ultrawide curved monitor displaying colorful code editor with syntax highlighting, steaming hot coffee in large ceramic mug on wooden desk, focused happy working expression, warm lamp light, compact centered desk setup`,

  march: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} running at full sprint on scenic forest trail, dynamic running form, wearing bright neon green running shirt, black running shorts, bright orange running shoes, holding open MacBook laptop in both hands while running, looking at screen with intense focused expression while sprinting, cherry blossom petals floating in golden morning sunlight, energetic spring morning run, absurd multitasking coding while running, centered dynamic action pose`,

  april: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} riding sleek carbon fiber road bicycle at speed, wearing bright blue cycling jersey, black padded cycling shorts, white cycling shoes clicked into pedals, aerodynamic helmet, cycling sunglasses pushed up, MacBook laptop mounted on handlebars with screen facing rider, both hands typing on keyboard while cycling, looking at code on screen with focused expression, rolling green Tuscan countryside hills with wildflowers and cypress trees, absurd bike coding setup, centered cyclist action pose`,

  may: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} sitting cross-legged on plaid picnic blanket in sunny park, wearing basic navy blue t-shirt, light blue jeans rolled up at ankles, white sneakers pristine, MacBook Pro balanced on lap with VS Code open showing React code, stylish white wireless over-ear headphones on head clearly visible, takeaway flat white coffee cup from artisan cafe beside him, dappled golden sunlight through leafy oak tree above, wildflowers blooming nearby, ultimate vibe coding session outdoors, centered park scene`,

  june: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} treading water in crystal clear turquoise open water lake, head and shoulders above water, wearing bright orange swim cap on head, IMPORTANT: exactly one pair of clear swimming goggles pushed up on forehead resting on swim cap, no goggles on eyes, holding MacBook laptop above water with both hands keeping it dry, looking at screen with focused coding expression, water splashing around athletic shoulders, bright sunny day with sun sparkling on water surface, distant green treeline and mountains, absurdly coding while swimming in lake, centered in water`,

  july: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} standing on surfboard riding a perfect turquoise wave, athletic surfing stance, wearing bright coral board shorts, no shirt showing tanned athletic torso, bare feet gripping waxed surfboard, holding open MacBook laptop in both hands while surfing, looking at screen with focused coding expression while riding wave, huge excited grin, white spray from wave curl behind him, tropical palm trees on distant beach, golden hour sunset light, absurd surf coding, centered wave riding action`,

  august: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} sitting on parked vintage classic cafe racer motorcycle on scenic coastal overlook, straddling the bike with both feet on ground for balance, kickstand down, wearing stylish open face helmet on head, vintage leather motorcycle jacket unzipped showing white t-shirt, dark jeans, leather boots, MacBook laptop open on motorcycle fuel tank in front of him, both hands typing on keyboard while sitting on bike, looking down at screen with focused coding expression, stunning ocean cliff views in background, blue sky with wispy clouds, absurd roadside coding break on motorcycle, centered motorcycle scene`,

  september: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} focused at premium home office with clay pink walls and natural wood acoustic panels, wearing comfortable grey fleece hoodie, dark jeans, white sneakers, sitting in ergonomic office chair at wooden desk, MacBook Pro connected to curved ultrawide monitor displaying code editor, mechanical keyboard, multiple coffee mugs including one with Apple logo, over-ear headphones around neck, warm desk lamp, many lush green houseplants everywhere - large monstera deliciosa, hanging pothos, fiddle leaf fig, snake plants, small succulents on desk, plants thriving all around the workspace, productive work session after summer, centered desk setup`,

  october: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} exactly two legs exactly two feet, sitting casually in open front trunk frunk of beautiful classic 1960s Porsche 911 in British racing green, legs dangling over front bumper with license plate reading 1337 visible between legs, frunk lid open, small empty storage compartment no engine in front, wearing authentic oil-stained blue mechanic coveralls, sturdy work boots, IMPORTANT: exactly one iPhone held in left hand showing YouTube car repair tutorial on screen, IMPORTANT: metal wrench tool held in right hand, only one phone visible in entire scene, confused expression looking at phone screen, grease smudge on cheek, closed MacBook Pro on nearby vintage wooden workbench, classic red toolbox with drawers open revealing tools, vintage Porsche racing posters on garage wall, concrete garage floor with oil stains, debugging car and code simultaneously, centered garage scene`,

  november: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} exactly two legs exactly two feet, curled up deep in oversized leather reading armchair, wearing cozy burnt orange fleece pullover, soft jogger pants, thick wool hiking socks, holding MacBook Pro on lap with code editor open, round reading glasses on nose, large ceramic mug of hot steaming coffee on wooden side table, tall wooden bookshelf overflowing with programming and car books, rain streaking down large window with moody grey sky outside, warm reading lamp glow, lit candle on shelf, cozy coding afternoon, centered armchair scene`,

  december: `${LIGHT_BASE_STYLE}, ${CHARACTER_DESC} sitting lazily slouched on comfortable worn leather couch wearing red santa hat tilted on head, festive red christmas sweater with tacky reindeer pattern, comfortable flannel pajama pants, cozy thick wool socks, MacBook Pro open on lap showing code editor while simultaneously watching PDC World Darts Championship on large TV screen showing dartboard and player throwing, dart scoreboard visible, room is complete chaotic christmas mess, half-eaten cookies and crumbs scattered everywhere on couch and floor, empty cookie tin, magnificently decorated christmas tree with colorful lights and tinsel, pile of torn wrapping paper and opened presents strewn across floor, multiple empty mugs, comfortable christmas chaos vibes, centered cozy couch scene`,
};

// Dark mode: Relaxed aftermath scenes - crashed after intense work+activity combo
export const DARK_PROMPTS: Record<Month, string> = {
  january: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} sinking deep into plush leather armchair beside roaring crackling stone fireplace, wearing thick cream cable-knit Irish wool sweater comfortable dark pants cozy wool socks, very prominent visible ski goggle tan lines on face - bright white untanned raccoon eye area around eyes sharply contrasting with deeply sun-tanned bronze rest of face from skiing all day in bright sun, exhausted but satisfied expression, closed laptop resting on side table not glowing not smoking, holding wine glass in one hand, wine bottle and bubbling cheese fondue pot on rustic wooden table beside him, no ski goggles visible anywhere, baby blue ski jacket draped over chair arm, warm orange firelight casting cozy shadows, rustic Swiss mountain chalet atmosphere with wooden beams, shipped code and shredded powder, centered fireside scene`,

  february: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} sitting up in luxurious king bed propped against mountain of fluffy white pillows, cozy under thick white duvet and soft grey blankets, MacBook Pro open on lap with bright screen light dramatically illuminating focused concentrated face in dark room, wearing stylish tortoiseshell reading glasses and soft grey t-shirt, coding intently at 2am completely in the zone, wooden mid-century nightstand beside bed with hardcover book titled "Classic Porsche 911 Restoration Guide" and steaming ceramic mug of chamomile tea with honey, iPhone charging on nightstand showing 2:47 AM, soft warm bedside lamp casting gentle glow, peaceful dedicated late night coding session, rain pattering softly on window, centered bedroom scene`,

  march: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} lying flat on back on grass in relaxed starfish position arms and legs spread wide, slim athletic body, wearing bright neon running shirt dark running shorts, bright running shoes still on feet, peaceful exhausted expression with eyes closed after finishing race, MacBook Pro lying closed on grass beside him, empty plastic water bottle knocked over, energy gel packets scattered around, medal from race hanging around neck, phone showing PR notification, dramatic orange pink sunset sky after evening race, crushed the run and the sprint deadline, centered collapsed runner scene`,

  april: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} sitting frustrated on dusty gravel roadside next to sleek carbon fiber road bicycle standing upright on kickstand with very visibly flat deflated front tire clearly showing flat rubber against ground, wearing bright blue cycling jersey, black padded cycling shorts, white cycling shoes, aerodynamic helmet pushed back on head, holding iPhone with confused frustrated expression googling "how to fix flat tire", bike leaning slightly toward flat front wheel, mini hand pump and tire levers on ground beside him, golden evening sunset light, rolling countryside hills in background, middle of nowhere scenic road, can debug code but not a flat tire, centered roadside scene with bike prominently visible`,

  may: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} peacefully napping lying down flat on weathered wooden park bench on his back, slim athletic body horizontal, wearing basic olive green t-shirt light blue jeans rolled at ankles pristine white sneakers, closed MacBook Pro laptop lying flat on bench beside him next to his body, stylish sunglasses on relaxed sleeping face eyes closed, AirPods in ears, several crushed empty beer cans scattered on grass beneath bench, half-eaten sandwich in paper wrapper, beautiful warm golden sunset light filtering through leafy green oak trees, deployed to prod now deploying to dreamland, centered bench scene`,

  june: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} blissfully floating on giant bright pink inflatable flamingo pool float in glowing backyard swimming pool at night, wearing colorful tropical print swim trunks, no sunglasses, one hand lazily holding tropical mai tai cocktail with tiny paper umbrella, other hand holding iPhone screen facing toward his face with bright phone screen light illuminating his relaxed face in the dark, looking at phone screen with lazy content expression, bright orange swim cap tossed on pool edge, underwater LED pool lights casting magical turquoise glow, stars twinkling above, string lights around pool area, deep work then deep end, centered pool float scene`,

  july: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} peacefully asleep face down on large colorful Mexican blanket beach towel on golden sand, slim athletic body, wearing bright coral board shorts, barefoot with sand between toes, surfboard planted upright in sand nearby casting long shadow, leash still attached to ankle, MacBook Pro safely tucked in bag nearby, empty fresh coconut drink with bamboo straw tipped over, stylish sunglasses on sleeping face, beautiful dramatic orange pink purple sunset over calm ocean, small cooler with one beer bottle and one glass beside towel, wiped out from waves and webpack, centered beach nap scene`,

  august: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} deeply peacefully asleep in swaying woven rope hammock strung between two palm trees, slim athletic body, wearing unbuttoned bright floral Hawaiian shirt, light linen shorts, barefoot with feet crossed, beautiful restored vintage classic cafe racer motorcycle parked nearby with kickstand down clearly visible in background, stylish open face helmet resting on motorcycle seat, vintage leather motorcycle jacket draped over hammock edge, MacBook Pro closed resting on chest, empty tropical cocktail glass dangling loosely from completely relaxed hand about to drop, dreamy peaceful sleeping expression, magical warm fairy string lights twinkling in palm fronds above, millions of stars in clear tropical night sky, cruising and coding complete, centered hammock scene with motorcycle visible`,

  september: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} slumped asleep at wooden desk with face resting on large mechanical keyboard leaving key impressions on cheek, slim athletic body, wearing cozy grey fleece hoodie comfortable black sweatpants warm wool socks, clay pink walls with natural wood acoustic panels, closed MacBook Pro laptop connected via cable to massive 49 inch super ultrawide curved monitor glowing bright showing lines of unfinished code with cursor blinking, several empty coffee mugs on desk including Apple logo mug, open pizza box with single cold slice remaining, over-ear headphones fallen around neck, warm desk lamp still on casting glow on sleeping face, dark night visible through window showing city lights, crashed harder than production, centered desk scene`,

  october: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} exactly two legs exactly two feet, peacefully fast asleep lying back in open front trunk frunk of beautiful classic 1960s Porsche 911 in British racing green, frunk lid open, legs dangling lazily over front bumper with license plate reading 1337 visible between legs, head resting back in small frunk compartment eyes closed peaceful exhausted expression, wearing heavily oil-stained dirty blue mechanic coveralls with grease smears everywhere, black oil smudge on cheek and forehead, dirty hands with oil under fingernails, scuffed work boots, wrench still loosely held in relaxed hand, scattered tools and wrenches on concrete garage floor around car, open greasy pizza box and craft beer bottle with empty glass on nearby vintage wooden workbench, closed MacBook Pro on workbench, harsh overhead garage work light casting dramatic shadows, vintage Porsche racing posters on wall, oil-stained concrete floor, exhausted after debugging engines and APIs, centered garage frunk scene`,

  november: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} peacefully asleep curled up in oversized worn leather reading armchair inside cozy dry living room, slim athletic body, wearing cozy burnt orange fleece pullover soft grey jogger pants thick wool hiking socks, round tortoiseshell reading glasses slipped down nose askew, closed MacBook Pro resting folded on armchair arm rest, holding open hardcover book titled "How to Retire at 35" resting on chest with pages spread, wine glass and wine bottle on side table next to wooden cheese board with brie and crackers, large window visible showing heavy autumn rain falling OUTSIDE only exterior is wet interior is completely dry and warm, warm scented candles on bookshelf, refactored code and relaxation, centered armchair scene`,

  december: `${DARK_BASE_STYLE}, ${CHARACTER_DESC} exactly two arms exactly two hands, passed out face down on festive christmas dinner table, head resting sideways on folded arms on table, slim athletic body slumped in wooden dining chair, wearing festive red fair isle christmas sweater with reindeer pattern with visible gravy stains and cookie crumbs, comfortable flannel pants, cozy thick wool socks, peaceful deeply asleep expression with slight drool, closed MacBook Pro laptop pushed aside on table, messy aftermath of christmas feast on table with half-eaten turkey carcass and scattered roast potatoes and brussels sprouts and gravy boat and cranberry sauce, wine bottle nearly empty and wine glass knocked over with small red puddle, crumpled christmas crackers and paper crowns, magnificently decorated glowing christmas tree with hundreds of warm white lights in background, torn wrapping paper scattered on floor, food coma after deploying dessert, centered dinner table scene`,
};

export const MONTHS: Month[] = [
  'january', 'february', 'march', 'april', 'may', 'june',
  'july', 'august', 'september', 'october', 'november', 'december'
];
